name: lyfeofty
favicon: null
layout_spectrum: 0.0386030781082809
typography_spectrum: 0.4163656800519675
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.9983980883844197
  lightness: 0.8395760129205883
  saturation: 0.7243882881011814
  rhythmicContrast: 0.8388493729289621
purpose: []
