name: lyfeofty
favicon: null
layout_spectrum: 0.14506
typography_spectrum: 0.4163656800519675
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#363f5c'
    - '#ccc6d0'
    - '#5a5f7c'
    - '#a7a3b2'
  brandStrength: 0.125
  lightness: 0.4375
  saturation: 0.6875
  rhythmicContrast: 0.75
purpose: []
