name: lyfeofty
favicon: null
layout_spectrum: 0.14506
typography_spectrum: 0.4163656800519675
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e8e8e8'
    - '#040404'
    - '#c3c3c3'
    - '#373737'
    - '#585858'
  brandStrength: 0.125
  lightness: 0.3125
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
